name: mongo-db-container
version: '3.0'
services:
  blogapp:
    image: blogapp:latest
    container_name: blogapp
    ports:
      - 5000:5000
    networks:
      - mongo-network
    environment:
      - DB=${DB}
      - SCREATKEY=${SCREATKEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PORT=${PORT}
volumes:
  mongo_db:

networks:
  mongo-network:
