name: mongo-db-container
version: '3.0'
services:
  blogapp:
    image: blogapp:latest
    container_name: blogapp
    ports:
      - 5000:5000
    networks:
      - mongo-network
 
volumes:
  mongo_db:

networks:
  mongo-network:
