

name: azure-deploy

on:
  push:
    branches:
      - azure
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to azure ande deploy to az container reg
        uses: azure/docker-login@v1
        with: 
          login-server: blogappcontainerreg.azurecr.io
          username: ${{secerets.AZ_REGESTRY_USER}}
          password: ${{secerets.AZ_REGESTRY_PASSWORD}}
        run: |
          docker build --file Dockerfile --tag blogappcontainerreg.azurecr.io/blogApi:${{ github.sha }} .
          docker push blogappcontainerregistry.azurecr.io/blogApi:${{ github.sha }}

      