

name: azure-deploy

on:
  push:
    branches:
      - azure
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        name: Login to azure ande deploy to az container reg
        with: 
          login-server: blogappcontainerreg.azurecr.io
          username: ${{secrets.AZ_REGESTRY_USER}}
          password: ${{secrets.AZ_REGESTRY_PASSWORD}}
      
      - run: |
          docker build -t blogappcontainerreg.azurecr.io/blogapi:${{ github.sha }} ../../.
          docker push blogappcontainerregistry.azurecr.io/blogApi:${{ github.sha }}

      